<?php

declare(strict_types=1);

/*
 * APIWithComplexHeaderParametersLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace APIWithComplexHeaderParametersLib\Tests;

use APIWithComplexHeaderParametersLib\APIWithComplexHeaderParametersClient;
use APIWithComplexHeaderParametersLib\APIWithComplexHeaderParametersClientBuilder;
use Core\Types\CallbackCatcher;

class ClientFactory
{
    public static function create(CallbackCatcher $httpCallback): APIWithComplexHeaderParametersClient
    {
        $clientBuilder = APIWithComplexHeaderParametersClientBuilder::init();
        $clientBuilder = self::addConfigurationFromEnvironment($clientBuilder);
        $clientBuilder = self::addTestConfiguration($clientBuilder);
        return $clientBuilder->httpCallback($httpCallback)->build();
    }

    public static function addTestConfiguration(
        APIWithComplexHeaderParametersClientBuilder $builder
    ): APIWithComplexHeaderParametersClientBuilder {
        return $builder;
    }

    public static function addConfigurationFromEnvironment(
        APIWithComplexHeaderParametersClientBuilder $builder
    ): APIWithComplexHeaderParametersClientBuilder {
        $timeout = getenv('API_WITH_COMPLEX_HEADER_PARAMETERS_LIB_TIMEOUT');
        $numberOfRetries = getenv('API_WITH_COMPLEX_HEADER_PARAMETERS_LIB_NUMBER_OF_RETRIES');
        $maximumRetryWaitTime = getenv('API_WITH_COMPLEX_HEADER_PARAMETERS_LIB_MAXIMUM_RETRY_WAIT_TIME');
        $environment = getenv('API_WITH_COMPLEX_HEADER_PARAMETERS_LIB_ENVIRONMENT');

        if (!empty($timeout) && \is_numeric($timeout)) {
            $builder->timeout(intval($timeout));
        }

        if (!empty($numberOfRetries) && \is_numeric($numberOfRetries)) {
            $builder->numberOfRetries(intval($numberOfRetries));
        }

        if (!empty($maximumRetryWaitTime) && \is_numeric($maximumRetryWaitTime)) {
            $builder->maximumRetryWaitTime(intval($maximumRetryWaitTime));
        }

        if (!empty($environment)) {
            $builder->environment($environment);
        }

        return $builder;
    }
}
