<?php

declare(strict_types=1);

/*
 * APIWithComplexHeaderParametersLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace APIWithComplexHeaderParametersLib\Models\Builders;

use APIWithComplexHeaderParametersLib\Models\Bike;
use Core\Utils\CoreHelper;

/**
 * Builder for model Bike
 *
 * @see Bike
 */
class BikeBuilder
{
    /**
     * @var Bike
     */
    private $instance;

    private function __construct(Bike $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Bike Builder object.
     *
     * @param string $make
     * @param string $model
     * @param int $year
     * @param int $engineCapacity
     */
    public static function init(string $make, string $model, int $year, int $engineCapacity): self
    {
        return new self(new Bike($make, $model, $year, $engineCapacity));
    }

    /**
     * Initializes a new Bike object.
     */
    public function build(): Bike
    {
        return CoreHelper::clone($this->instance);
    }
}
