<?php

declare(strict_types=1);

/*
 * APIWithComplexHeaderParametersLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace APIWithComplexHeaderParametersLib\Models\Builders;

use APIWithComplexHeaderParametersLib\Models\Car;
use APIWithComplexHeaderParametersLib\Models\Engine;
use Core\Utils\CoreHelper;

/**
 * Builder for model Car
 *
 * @see Car
 */
class CarBuilder
{
    /**
     * @var Car
     */
    private $instance;

    private function __construct(Car $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Car Builder object.
     *
     * @param string $make
     * @param string $model
     * @param int $doors
     * @param Engine $engine
     */
    public static function init(string $make, string $model, int $doors, Engine $engine): self
    {
        return new self(new Car($make, $model, $doors, $engine));
    }

    /**
     * Initializes a new Car object.
     */
    public function build(): Car
    {
        return CoreHelper::clone($this->instance);
    }
}
