<?php

declare(strict_types=1);

/*
 * APIWithComplexHeaderParametersLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace APIWithComplexHeaderParametersLib\Models\Builders;

use APIWithComplexHeaderParametersLib\Models\Engine;
use Core\Utils\CoreHelper;

/**
 * Builder for model Engine
 *
 * @see Engine
 */
class EngineBuilder
{
    /**
     * @var Engine
     */
    private $instance;

    private function __construct(Engine $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Engine Builder object.
     *
     * @param int $horsepower
     * @param string $fuelType
     */
    public static function init(int $horsepower, string $fuelType): self
    {
        return new self(new Engine($horsepower, $fuelType));
    }

    /**
     * Initializes a new Engine object.
     */
    public function build(): Engine
    {
        return CoreHelper::clone($this->instance);
    }
}
