<?php

declare(strict_types=1);

/*
 * APIWithComplexHeaderParametersLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace APIWithComplexHeaderParametersLib\Models\Builders;

use APIWithComplexHeaderParametersLib\Models\PaypalMockResponseSchema;
use Core\Utils\CoreHelper;

/**
 * Builder for model PaypalMockResponseSchema
 *
 * @see PaypalMockResponseSchema
 */
class PaypalMockResponseSchemaBuilder
{
    /**
     * @var PaypalMockResponseSchema
     */
    private $instance;

    private function __construct(PaypalMockResponseSchema $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Paypal Mock Response Schema Builder object.
     *
     * @param string $mockApplicationCodes
     */
    public static function init(string $mockApplicationCodes): self
    {
        return new self(new PaypalMockResponseSchema($mockApplicationCodes));
    }

    /**
     * Initializes a new Paypal Mock Response Schema object.
     */
    public function build(): PaypalMockResponseSchema
    {
        return CoreHelper::clone($this->instance);
    }
}
