<?php

declare(strict_types=1);

/*
 * APIWithComplexHeaderParametersLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace APIWithComplexHeaderParametersLib\Models\Builders;

use APIWithComplexHeaderParametersLib\Models\SuccessResponse;
use Core\Utils\CoreHelper;

/**
 * Builder for model SuccessResponse
 *
 * @see SuccessResponse
 */
class SuccessResponseBuilder
{
    /**
     * @var SuccessResponse
     */
    private $instance;

    private function __construct(SuccessResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Success Response Builder object.
     */
    public static function init(): self
    {
        return new self(new SuccessResponse());
    }

    /**
     * Sets message field.
     *
     * @param string|null $value
     */
    public function message(?string $value): self
    {
        $this->instance->setMessage($value);
        return $this;
    }

    /**
     * Initializes a new Success Response object.
     */
    public function build(): SuccessResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
