<?php

declare(strict_types=1);

/*
 * APIWithComplexHeaderParametersLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace APIWithComplexHeaderParametersLib\Models\Builders;

use APIWithComplexHeaderParametersLib\Models\Engine;
use APIWithComplexHeaderParametersLib\Models\Vehicle;
use Core\Utils\CoreHelper;

/**
 * Builder for model Vehicle
 *
 * @see Vehicle
 */
class VehicleBuilder
{
    /**
     * @var Vehicle
     */
    private $instance;

    private function __construct(Vehicle $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Vehicle Builder object.
     *
     * @param string $make
     * @param string $model
     * @param int $year
     * @param Engine $engine
     */
    public static function init(string $make, string $model, int $year, Engine $engine): self
    {
        return new self(new Vehicle($make, $model, $year, $engine));
    }

    /**
     * Initializes a new Vehicle object.
     */
    public function build(): Vehicle
    {
        return CoreHelper::clone($this->instance);
    }
}
